- hosts: dev
  become: no
  gather_facts: no
  serial: 1
  roles:
    - update
    - install_elasticsearch
    - install_kibana
    - install_logstash

- hosts: test
  become: no
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - update


- hosts: staging
  become: no
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - update


- hosts: prod
  become: no
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - update
