- hosts: dev
  become: no
  gather_facts: no
  connection: local
  roles:
    - resource_group
    - virtual_networks
    - subnets
    - virtual_machines

- hosts: test
  become: no
  gather_facts: no
  connection: local
  roles:
    - resource_group
    - virtual_networks
    - subnets
    - virtual_machines


- hosts: staging
  become: no
  gather_facts: no
  connection: local
  roles:
    - resource_group
    - virtual_networks
    - subnets
    - virtual_machines


- hosts: prod
  become: no
  gather_facts: no
  connection: local
  roles:
    - resource_group
    - virtual_networks
    - subnets
    - virtual_machines
