- debug:
    msg: "Creating security groups"


- name: Create security group that allows SSH and HTTP
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: secgroup002
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 102
        direction: Inbound

- name: Create security group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: secgroup001
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound

