- debug:
    msg: "Creating storage accounts"


- name: Create storage account
  azure_rm_storageaccount:
    resource_group: "{{ resource_group }}"
    name: "{{ storage_account }}"
    account_type: Standard_LRS

