- name: copying rpm files
  copy:
    src: rpms
    dest: /tmp/
    owner: admina
    group: admina
    mode: 0644

- name: install java rpm from a local file
  become: true
  yum:
    name: /tmp/rpms/jdk-8u181-linux-x64.rpm
    state: present


- name: add elasticsearch public GPG key
  become: true
  rpm_key:
    state: present
    key: http://packages.elastic.co/GPG-KEY-elasticsearch


- name: Add yum repository for logstash
  become: true
  yum_repository:
    name: logstash-2.2
    description: logstash repository for 2.2 packages
    file: logstash
    baseurl: http://packages.elasticsearch.org/logstash/2.2/centos
    gpgcheck: yes
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes


- name: install the latest version of logstash
  become: true
  yum:
    name: logstash
    state: latest

- name: Restart service logstash, in all cases
  become: true
  service:
    name: elasticsearch
    state: restarted
    enabled: yes


